version: "3"
services:
    app:
        build:
            context: .
            dockerfile: ./instatonne-frontend/Dockerfile
        image: timgrohmann/it-app:1
        ports:
            - "80:80"
        deploy:
            replicas: 1
    spring:
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        image: timgrohmann/it-backend:1
        ports:
            - "8080:8080"
        deploy:
            replicas: 1
