info:
  title: Instatonne
  description: Instagram, aber für die Tonne
  license:
    name: Apache 2.0
    url: https://github.com/OAI/OpenAPI-Specification/blob/master/https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
openapi: "3.0.3"
tags:
  - name: posts
  - name: users
  - name: messages
paths:
  "/p":
    get:
      summary: Returns a list of posts.
      operationId: getPosts
      tags:
        - posts
      responses:
        "200":
          description: Successfully retrieved posts.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"
    post:
      summary: Create a new.
      operationId: createPost
      tags:
        - posts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewPost"
      responses:
        "200":
          description: Successfully created post.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
  "/p/{postId}":
    get:
      summary: Returns a single post by id.
      operationId: getPostById
      tags:
        - posts
      parameters:
        - in: path
          name: postId
          schema:
            type: string
          required: true
          description: The post id in uuid format
      responses:
        "200":
          description: Successfully retrieved post.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
        "404":
          $ref: "#/components/responses/NotFound"
  "/p/{postId}/i.jpg":
    get:
      summary: Returns the image of a post.
      operationId: getPostImageById
      tags:
        - posts
      parameters:
        - in: path
          name: postId
          schema:
            type: string
          required: true
          description: The post id in uuid format
      responses:
        "200":
          description: Successfully retrieved image.
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
        "404":
          $ref: "#/components/responses/NotFound"
  "/u":
    get:
      summary: Returns a single user by username.
      operationId: searchUsers
      tags:
        - users
      parameters:
        - in: query
          name: searchTerm
          schema:
            type: string
          required: true
          description: The username to search for.
      responses:
        "200":
          description: Successfully retrieved users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "404":
          $ref: "#/components/responses/NotFound"
  "/u/{username}":
    get:
      summary: Returns a single user by username.
      operationId: getUserByName
      tags:
        - users
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: The user's username.
      responses:
        "200":
          description: Successfully retrieved user.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          $ref: "#/components/responses/NotFound"
  "/u/{username}/p":
    get:
      summary: Returns all posts of an user by username
      operationId: getPostsByUserName
      tags:
        - users
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: The user's username.
      responses:
        "200":
          description: Successfully retrieved posts of user.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"
        "404":
          $ref: "#/components/responses/NotFound"
  "/u/{username}/f":
    get:
      summary: Gets a users list of followers.
      operationId: getFollowersForUsername
      tags:
        - users
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: The username to get followers for.
      responses:
        "200":
          description: A list of followers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "404":
          $ref: "#/components/responses/NotFound"
    put:
      summary: Follows a user specified by username.
      operationId: followUserWithName
      tags:
        - users
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: The username of the user to follow.
      responses:
        "200":
          description: The updated user that has been followed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          $ref: "#/components/responses/NotFound"
    delete:
      summary: Unfollows a user specified by username.
      operationId: unfollowUserWithName
      tags:
        - users
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: The username of the user to unfollow.
      responses:
        "200":
          description: The updated user that has been unfollowed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          $ref: "#/components/responses/NotFound"
  "/u/{username}/s":
    get:
      summary: Gets a list of users the user follows.
      operationId: getFollowingForUsername
      tags:
        - users
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: The username to get subscribed users for.
      responses:
        "200":
          description: A list of subscribed users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "404":
          $ref: "#/components/responses/NotFound"
  "/u/me":
    get:
      summary: Returns the user identified by the token.
      operationId: getUserMe
      tags:
        - users
      responses:
        "200":
          description: Successfully retrieved user.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          $ref: "#/components/responses/NotFound"
    put:
      summary: Update the user currently signed in user.
      operationId: updateUser
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: Updated version of the user.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          $ref: "#/components/responses/NotFound"
  "/u/create":
    post:
      summary: Creates a new user.
      operationId: createNewUser
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewUser"
      responses:
        "200":
          description: Successfully created user.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          $ref: "#/components/responses/NotFound"
  "/m":
    get:
      summary: Retrieves all conversations a user has.
      operationId: getConversations
      tags:
        - messages
      responses:
        "200":
          description: An array of conversations.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Conversation"
  "/m/{username}":
    get:
      summary: Retrieves all messages in the conversation with {username}
      operationId: getMessagesWithUser
      tags:
        - messages
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: The username to get subscribed users for.
      responses:
        "200":
          description: An array of messages.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Message"
    post:
      summary: Sends a new message.
      operationId: sendMessageToUser
      tags:
        - messages
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: The username to get subscribed users for.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewMessage"
      responses:
        "200":
          description: The message that was sent.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "404":
          $ref: "#/components/responses/NotFound"
components:
  schemas:
    User:
      properties:
        id:
          type: string
        username:
          type: string
        altName:
          type: string
        profileDescription:
          type: string
        created:
          type: string
          format: date-time
        profilePictureUrl:
          type: string
        followerCount:
          type: integer
        followingCount:
          type: integer
        isBeingFollowed:
          type: boolean
        isFollowingMe:
          type: boolean
        isSelf:
          type: boolean
    NewUser:
      properties:
        username:
          type: string
        profileDescription:
          type: string
    Post:
      properties:
        id:
          type: string
        created:
          type: string
          format: date-time
        author:
          type: string
        imageUrl:
          type: string
        likeCount:
          type: integer
        comments:
          type: array
          items:
            $ref: "#/components/schemas/Comment"
    NewPost:
      properties:
        text:
          type: string
        image:
          description: A base64 encoded version of the image in jpg format
          type: string
          format: base64
    Message:
      properties:
        id:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time
        author:
          type: string
          description: The username of the message's sender.
        receiver:
          type: string
          description: The recipient's username.
    NewMessage:
      properties:
        message:
          type: string
    Conversation:
      properties:
        withUser:
          $ref: "#/components/schemas/User"
        lastMessage:
          $ref: "#/components/schemas/Message"
        unreadMessageCount:
          type: integer
    Comment:
      properties:
        created:
          type: string
          format: date-time
        author:
          type: string
        comment:
          type: string
  responses:
    NotFound:
      description: The specified resource was not found.
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - jwtAuth: []
