name: Tests

# Trigger on push
on: push

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: jUnit Tests
        run: mvn --no-transfer-progress test
        working-directory: backend
